version: "3.9"

services:

  reverse-proxy:
    build: reverse_proxy
    ports:
        - "80:80"
        - "443:443"
    volumes:
      - ./certs:/certs

  home:
    build: home
    expose:
      - 80

  site1:
    build: site1
    expose:
      - 80